services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    ports:
      - "8080:8000"
    volumes:
      - ./.env:/var/www/.env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

volumes:
  mysql_data:
